# Generated by Django 6.0.4 on 2026-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
