# Generated by Django 6.0.4 on 2026-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
